#Requires -RunAsAdministrator

@'
# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
'@ | Out-FileUtf8NoBom ($a = 'C:\Users\Default\.bash_profile')
if (!(Test-Path ($b = "$env:USERPROFILE\.bash_profile"))) {
    Copy-Item $a $b
}
else {
    Write-MergeAdviceIfDifferent $a $b
}

$templ = Get-Content -ea 0 -raw '.bashrc'
if ($templ) {
    $txt = $templ
    $txt | Out-FileUtf8NoBom ($a = 'C:\Users\Default\.bashrc')

    if (!(Test-Path ($b = "$env:USERPROFILE\.bashrc"))) {
        Copy-Item $a $b
    }
    else {
        Write-MergeAdviceIfDifferent $a $b
    }
}
