#Requires -RunAsAdministrator

@'
# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
'@ | Out-FileUtf8NoBom ($defaultProfile = 'C:\Users\Default\.bash_profile')

if (!(Test-Path ($currentProfile = "$env:USERPROFILE\.bash_profile"))) {
    Copy-Item $defaultProfile $currentProfile
}
else {
    Write-MergeAdviceIfDifferent $defaultProfile $currentProfile
}

$templ = Get-Content -ea 0 -raw '.bashrc'
if ($templ) {
    $txt = $templ
    $txt | Out-FileUtf8NoBom ($defaultRc = 'C:\Users\Default\.bashrc')

    if (!(Test-Path ($currentRc = "$env:USERPROFILE\.bashrc"))) {
        Copy-Item $defaultRc $currentRc
    }
    else {
        Write-MergeAdviceIfDifferent $defaultRc $currentRc
    }
}
